import { GetServerSideProps } from "next";
import { redirect } from "next/dist/server/api-utils";
import Head from "next/head";
import { useEffect } from "react";
import { Header, Hero, Modal, Row, SubscriptionPlan } from "src/components";
import { getList } from "src/helpers/lists";
import { IMovie, MyList, Product } from "src/interfaces/app.interface";
import { API_REQUEST } from "src/services/api.service";
import { useInfoState } from "src/store";

export default function Home({
  trending,
  topRated,
  tvTopRated,
  popular,
  comedy,
  documentary,
  family,
  history,
  products,
  subscription,
  list,
}: HomeProps): JSX.Element {
  console.log(list);
  const { modal } = useInfoState();
  if (!subscription.length) {
    return <SubscriptionPlan products={products} />;
  }

  return (
    <div
      className={`relative min-h-screen ${
        modal && "!h-screen overflow-hidden"
      }`}
    >
      <Head>
        <title>Home - Kuchkarov</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main className="relative pl-4 pb-24 lg:space-y-24 lg:pl-16">
        <Hero trending={trending} />
        <section>
          <Row title="Top Rated" movies={topRated}></Row>
        </section>
        <section>
          <Row title="Feature Tv Show" isBig={true} movies={tvTopRated}></Row>
        </section>
        {list.length && (
          <section>
            <Row title="My List" movies={list}></Row>
          </section>
        )}
        <section>
          <Row title="Popular films" movies={popular}></Row>
        </section>
        <section>
          <Row title="Documentary" movies={documentary}></Row>
        </section>
        <section>
          <Row title="Comedy" movies={comedy}></Row>
        </section>
        <section>
          <Row title="Family" movies={family}></Row>
        </section>
        <section>
          <Row title="History" movies={history}></Row>
        </section>
      </main>
      {modal && <Modal />}
    </div>
  );
}
export const getServerSideProps: GetServerSideProps<HomeProps> = async ({
  req,
}) => {
  const user_id = req.cookies.user_id;
  if (!user_id) {
    return {
      redirect: { destination: "/auth", permanent: false },
    };
  }
  const [
    trending,
    topRated,
    tvTopRated,
    popular,
    documentary,
    comedy,
    family,
    history,
    { products },
    { subscription },
  ] = await Promise.all([
    fetch(API_REQUEST.trending).then((res) => res.json()),
    fetch(API_REQUEST.top_rated).then((res) => res.json()),
    fetch(API_REQUEST.tv_top_rated).then((res) => res.json()),
    fetch(API_REQUEST.popular).then((res) => res.json()),
    fetch(API_REQUEST.documentary).then((res) => res.json()),
    fetch(API_REQUEST.comedy).then((res) => res.json()),
    fetch(API_REQUEST.family).then((res) => res.json()),
    fetch(API_REQUEST.history).then((res) => res.json()),
    fetch(API_REQUEST.product_list).then((res) => res.json()),
    fetch(`${API_REQUEST.subscription}/${user_id}`).then((res) => res.json()),
  ]);
  const myList: MyList[] = await getList(user_id);
  return {
    props: {
      trending: trending.results,
      topRated: topRated.results,
      tvTopRated: tvTopRated.results,
      popular: popular.results,
      documentary: documentary.results,
      comedy: comedy.results,
      family: family.results,
      history: history.results,
      products: products.data,
      subscription: subscription?.data,
      user_id,
      list: myList?.map((item) => item.product as IMovie),
    },
  };
};
interface HomeProps {
  trending: IMovie[];
  topRated: IMovie[];
  tvTopRated: IMovie[];
  popular: IMovie[];
  documentary: IMovie[];
  comedy: IMovie[];
  family: IMovie[];
  history: IMovie[];
  products: Product[];
  subscription: any;
  user_id?: string;
  list: IMovie[];
}
